### ISSUE TITLE
Final Metric Calculation in Code

### ISSUE THREAD

**Issue by elenabbbuenob** [mingu6/action_seg_ot#1]
Hello, 
I hope you're doing well! I've been working with the code and have a couple of queries I'd like to discuss.
It appears that the current code calculates metrics on a per-activity basis. Could you confirm if the MOF metric is averaged per activity, or if it's calculated as the overall mean of correctly classified frames over total frames?
If the calculation involves averaging MOF scores per activity, I've observed some discrepancies between the BF and YTI datasets. Notably, the differences in the YTI dataset are quite significant.

I'd appreciate your insights on these points. Clarifying the intended methodology and addressing any inconsistencies would greatly assist in ensuring the accuracy of our results.

**Comment by mingu6** [comment]
Hi,

The MoF metric is calculated as the overall mean, not averaging MoF per activity. I did this manually instead of in the code. This is also what we report for the reproduced version of CTE in the paper.

**Comment by mingu6** [comment]
Closed.
